### ISSUE TITLE
Cordova 5.4.0 changed the way args are passed in, requires tweak to getCallArgs in ttb-util.js

### ISSUE THREAD

**Issue by Chuxel** [Microsoft/taco-team-build#10]
So, for some reason the way arguments get passed into commands line build changed in 5.4.0 so this breaks our extension – likely the same problem I’ve heard we have for VS TACO and TACO CLI. 

Before:

cordova.build({
platforms: ["android"],
options: ["--ant", "--gradleArg=--no-daemon"]
}, callback);

After:
cordova.build({
platforms: ["android"],
options: {
argv: ["--ant", "--gradleArg=--no-daemon"]
}
}, callback);

Here’s what you see with 5.4.0 right now:

Running: C:\a\1\s\tfs-vnext-test\platforms\android\gradlew cdvBuildDebug -b C:\a\1\s\tfs-vnext-test\platforms\android\build.gradle -Dorg.gradle.daemon=true

And the same thing with 5.3.3:

Running: C:\a\1\s\tfs-vnext-test\platforms\android\gradlew cdvBuildRelease -b C:\a\1\s\tfs-vnext-test\platforms\android\build.gradle -Dorg.gradle.daemon=true --no-daemon

Builds work, but are not doing the right thing since the args don’t make it through.  Builds are also always “debug” right now with 5.4.0.

**Comment by MSLaguana** [comment]
There's a Cordova issue tracking this API change, and they're working out the best way to proceed. You can follow it here https://issues.apache.org/jira/browse/CB-9987

I believe that the current plan is to do up a compatibility layer, so the next version of Cordova may support the previous arguments again, but this issue will persist for cordova 5.4.0.  Also depending on how things are addressed, you may not be able to work with the android 5.0.0 platform since it expects the new argument format.

**Comment by Chuxel** [comment]
Yeah I think the best approach is going to be to switch to the new arg format if we detect 5.4.0+. It seems highly unlikely that they'd completely drop support for {argv:[]}. Compatibility would be easy to add by simply detecting if options is an array and wrapping it in an object and skipping that step if an object is found.

**Comment by Chuxel** [comment]
Resolved.

**Comment by kamakshi417** [comment]
when i install any plugin using cordova cli all files(html ,js and .css files) which are in platforms(present i installed android ) are override with www folder files.

**Comment by Chuxel** [comment]
Plugin installation runs "prepare" which will do this in all cases.  Your source code should be in the root www folder.
